# Generated by Django 3.2 on 2022-03-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('imagen', models.ImageField(blank=True, upload_to='img/', verbose_name='Image')),
                ('ffecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizar', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-id'],
            },
        ),
    ]
